# ./.github/actions/blank/action.yml
name: 'Maven Build'

inputs:
  runs-on:
    description: "Defines the type of machine to run the job on"
    required: true
    type: string
  param1:
    description: "The Java version that is going to be set up."
    required: true
    type: number
  param2:
    description: "JFrog Artifactory URL"
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: clean workspace
      run: |
        rm -rf ${{ github.workspace }}/*

    - name: print variables
      run: |
        echo "param1: ${{ inputs.param1 }}"
        echo "param2: ${{ inputs.param2 }}"