# ./.github/workflows/main.yml
name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1'
        required: true
      param2:
        description: 'Parameter 2'
        required: true

jobs:
    build:
        uses: ./.github/workflows/blank.yml@main
        with:
          param1: ${{ github.event.inputs.param1 }}
          param2: ${{ github.event.inputs.param2 }}

    deploy:
      uses: ./.github/workflows/blank1.yml@main
      with:
        param1: ${{ github.event.inputs.param1 }}
        param2: ${{ github.event.inputs.param2 }}        