name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1'
        required: true
      param2:
        description: 'Parameter 2'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Maven Build
        uses: ./.github/workflows/blank.yml
        with:
          param1: ${{ github.event.inputs.param1 }}
          param2: ${{ github.event.inputs.param2 }}