name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1'
        required: true
      param2:
        description: 'Parameter 2'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: Run my job
        uses: ./.github/workflows/blank.yml
      
         
