name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1'
        required: true
      param2:
        description: 'Parameter 2'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
       
      - name: permissions
        run:  |
            chmod +x ./.github/workflows/blank.yml

      - name: Run my job
        run: ./.github/workflows/blank.yml
